name: Build
on:
  workflow_call:
    secrets:
        TOKEN1:
          required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.TOKEN1 }}
        echo "Value of Test : ${{ github.event.inputs.param1 }}"
