on:
  workflow_dispatch:
    inputs:
        param1:
          description: "Test"
          required: false
          default: "World"
jobs:
  build_workflow:
    uses: ./.github/workflows/build.yml
    secrets:
      TOKEN1: ${{ secrets.TOKEN1 }}
      
